### ISSUE TITLE
Intro to Graphics chapter should come before Anim Chapter? and other related redundancies...

### ISSUE THREAD

**Issue by Onna-no-hito** [openframeworks/ofBook#11]
Intro to graphics should come before the anim chapter, or? that way x/y coordinate system and drawing to screen are already discussed before talking about how to animate objects on screen.

although-- Zach are you covering those two topics in the Intro?

you wrote:
setup/update/draw
first project a circle moving in the screen

i feel there might be some overlap between Zach (Intro/Anim), Mike (Intro to Graphics) and Mike, some things you propose which Golan (Image Processing) might be covering.
You (Mike) seem to be touching on a lot of topics--

can you guys please  look over each other's outlines and see where there might be redundancies? thanks!

**Comment by tpltnt** [comment]
Is this still an issue to be worked on? If not, please close it.
