### ISSUE TITLE
Wrong variable name in creating brush with polylines

### ISSUE THREAD

**Issue by gerbyzation** [openframeworks/ofBook#110]
There is a small mixup of variable names in the Graphics chapter about creating a brush with polylines:
"Initialize minDistance and currentedAddingPoints in setup():
`minDistance = 10;
currentlyAddingPoints = false;`"

should be: 
`minDistance = 10;
leftMouseButtonPressed = false;`

**Comment by mikewesthad** [comment]
@gerbyzation thanks for catching that! I'll fix it tonight.
