### ISSUE TITLE
Order and Flow

### ISSUE THREAD

**Issue by mikewesthad** [openframeworks/ofBook#12]
I think it would be a good time to start talking about chapter order and the flow of reading.

After the reading the outlines, I see there are a few core chapters that need to be read in order, and then the others can be read in whatever order the reader prefers.  (I'm thinking about absolute beginners here.)

Here's a suggested order of chapters to get people making openFrameworks apps as quickly as possible (important), while also covering the cores:

1. Intro
2. C++ Basics
3. Setup and Project Structure
4. Introduction to Graphics 
  - I won't be using much that isn't already covered by C++ and Setup other than vectors
5. OOPs!
6. Animation
  - @ofZach, this chapter has OOP I assume; otherwise, it could come before the OOP chapter
7. Advanced Graphics
8. Memory
9. Network
10. Threads

The rest of the chapters can be explored however the reader feels like exploring.  There is probably some sort of progression in terms of difficulty that could be used to organize these chapters, but I'm just listing them arbitrarily:

- Image Processing Computer Vision
- Game Design
- Hardware
- Sound
- iOS
- Android
- Version Control
- Shaders
- Project Elliot
- Project Eva
- Project Joel
- Project Memo

Some chapters are currently blank, so I left them out:

- Media
- Interaction Leaving the Screen
- Data Vis
- Arm Linux
- C++11

**Comment by tpltnt** [comment]
Is this still an issue given that there is a "order.txt" file in the "chapters" directory? If there isn't any veto, this issue should be closed.

**Comment by bilderbuchi** [comment]
I think this can safely be closed, chapter order is pretty mature already.
