### ISSUE TITLE
TOC not showing up on website

### ISSUE THREAD

**Issue by mattfelsen** [openframeworks/ofBook#121]
Hey @ofZach, did you ever get a chance to look into why the new TOC doesn't appear on openframworks.cc? Let me know if I can help troubleshoot.

http://openframeworks.cc/ofBook/chapters/toc.html

Curious if anyone else is having trouble when running `python createWebBook.py` since last weekend. :fearful:

**Comment by ofZach** [comment]
it's something having to do with the pandoc call to generate the TOC page, it's fine on OSX but it's not happy on the server -- I see "pandoc: Could not find data file templates/default.html"

it might be better to not use pandoc (which here seems only to just be adding headers and footers) and to do this by hand using the template files.  I'll take a look tomorrow.

**Comment by mattfelsen** [comment]
That makes sense, but is still odd...I tried adding --template=createWebBookTemplate/default.html to the pandoc call but that didn't seem to fix it.

There's some stuff that gets parsed by pandoc in default.html that I didn't want to duplicate in a second, static include file, but I guess that's an easy solution to this. Whenever you take a look, let me know if that seems right and I can update the script.

**Comment by mikewesthad** [comment]
Which OSes does the script have trouble with - is it just linux?  It's running fine on windows for me.

**Comment by tpltnt** [comment]
I can create the webbook (incl. TOC) just fine on Debian as of today.

**Comment by ofZach** [comment]
there is something wrong on the server where the OF book is running so this TOC doesn't get made, I will take another look.

**Comment by tpltnt** [comment]
@ofZach did you find anything?
