### ISSUE TITLE
"oF" or "OF"

### ISSUE THREAD

**Issue by tpltnt** [openframeworks/ofBook#134]
Hello ofBook people,
currently there are two abbreviations floating around for "openFrameworks", namely "oF" and "OF". I personally prefer "oF" since it mimics the name **o**pen**F**rameworks. "OF" on the other hand seems to mimic the icon. Which one should be settled on for this book?

**Comment by bilderbuchi** [comment]
@ofZach I think arrived at some conclusion already.
Personally, I prefer oF for the consistency reason you cite.

**Comment by mikewesthad** [comment]
Ditto to "oF" as opposed to "OF," though I prefer the unabbreviated "openFrameworks" to both for the book

**Comment by ofZach** [comment]
personally "oF" makes my ocd go crazy, but I think the community has pretty widely adopted this over "OF" so I've come to terms with it.

**Comment by bakercp** [comment]
And then of course there's ofxAddons and ofSketch just to confuse things a little.  I understand the allergic oCD reaction to "oF" -- it kind of reminds me of the early processing / aka p5 days discussion -- but I also think "oF" is more distinctive (the appearance of intentionality/design) than "OF", which (in addition to the other reasons cited above) makes me throw a vote in the "oF" direction.  This could be illusory of course ...  

Next we can decide how to apply camel case to variable names and class names when acronyms and abbreviations are involved. That'll be a fun discussion :)

**Comment by elliotwoods** [comment]
which is the one implemented by the oF gang sign?

On 24 April 2015 at 16:42, Christopher Baker <notifications@github.com>
wrote:

> And then of course there's ofxAddons and ofSketch just to confuse things a
> little. I understand the allergic oCD reaction to "oF" -- it kind of
> reminds me of the early processing / aka p5 days discussion -- but I also
> think "oF" is more distinctive (the appearance of intentionality/design)
> than "OF", which (in addition to the other reasons cited above) makes me
> throw a vote in the "oF" direction. This could be illusory of course ...
>
> Next we can decide how to apply camel case to variable names and class
> names when acronyms and abbreviations are involved. That'll be a fun
> discussion :)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/openframeworks/ofBook/issues/134#issuecomment-95951639>
> .
>



-- 
-- 
Elliot Woods
elliot <elliot@kimchiandchips.com>@KimchiAndChips.com
<http://www.kimchiandchips.com/>

UK : +447944977628
KR : +821034458086

**Comment by JGL** [comment]
oF for sure!

x
> On 24 Apr 2015, at 15:44, Elliot Woods <notifications@github.com> wrote:
> 
> which is the one implemented by the oF gang sign?
> 
> On 24 April 2015 at 16:42, Christopher Baker <notifications@github.com>
> wrote:
> 
> > And then of course there's ofxAddons and ofSketch just to confuse things a
> > little. I understand the allergic oCD reaction to "oF" -- it kind of
> > reminds me of the early processing / aka p5 days discussion -- but I also
> > think "oF" is more distinctive (the appearance of intentionality/design)
> > than "OF", which (in addition to the other reasons cited above) makes me
> > throw a vote in the "oF" direction. This could be illusory of course ...
> >
> > Next we can decide how to apply camel case to variable names and class
> > names when acronyms and abbreviations are involved. That'll be a fun
> > discussion :)
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/openframeworks/ofBook/issues/134#issuecomment-95951639>
> > .
> >
> 
> 
> 
> -- 
> -- 
> Elliot Woods
> elliot <elliot@kimchiandchips.com>@KimchiAndChips.com
> <http://www.kimchiandchips.com/>
> 
> UK : +447944977628
> KR : +821034458086
> —
> Reply to this email directly or view it on GitHub.
> 


Joel Gethin Lewis
me@joelgethinlewis.com
@joelgethinlewis
+44 7932 792 076

**Comment by bilderbuchi** [comment]
> Next we can decide how to apply camel case to variable names and class names when acronyms and abbreviations are involved. That'll be a fun discussion :)

+1, everytime I see some `ofxiOSC***` name, I think "oh, some OSC stuff", when in fact it's some iOS thing starting with "C" ^^
However, we explicitly declare our code style as derived from the [Qt style](https://wiki.qt.io/Qt_Coding_Style), and that one (now) contains a clause for this (which we don't have in the OF style spec yet):
> Acronyms are camel-cased (e.g. QXmlStreamReader, not QXMLStreamReader).

**Comment by bilderbuchi** [comment]
closed by #135
