### ISSUE TITLE
take out the debug builds from repo

### ISSUE THREAD

**Issue by lewislepton** [openframeworks/ofBook#136]
just to say that the download is big, on looking it seems that there are debug builds of the examples. would be best to take these out ;)

**Comment by bilderbuchi** [comment]
+1, any compiled code in the repo shouldn't be in there, imo.

**Comment by mikewesthad** [comment]
I second that.  

But the debug builds aren't the reason the download is big.  The C++ Basics  and Game Design chapters seem to be the largest.  E.g. there's a >11mb pdf in the C++ folder.  @jtnimoy & @phoenixperry - would you mind taking a look to see if we can trim any files?

**Comment by tpltnt** [comment]
:+1:

**Comment by tpltnt** [comment]
@jtnimoy given [commit d827bd7fb8fe0fd591317656920346664c25c60e](https://github.com/openframeworks/ofBook/commit/d827bd7fb8fe0fd591317656920346664c25c60e) I assume i can delete the two pdf files from the c++ basics directors?
