### ISSUE TITLE
create a pdf not working on osx

### ISSUE THREAD

**Issue by mattholl** [openframeworks/ofBook#140]
Running the command:

`python createPDFBook.py`

gives the following error:

    Successful building of ../output/ofBook.tex
    pandoc: xelatex not found. xelatex is needed for pdf output.
    Error in building of ../output/ofBook.pdf

I'm on OS X 10.10, I've installed the dependencies according the Readme with brew - mactex and basictex appeared to install fine. 

I can't find xelatex on homebrew, is there a specific way to install this dependency?

Thanks

**Comment by bilderbuchi** [comment]
Unfortunately, [the current focus](https://github.com/openframeworks/ofBook/pull/105#issuecomment-74403968) is not on the pdf version, so that is broken atm I think. however, maybe @ofZach @mikewesthad can shed some light on how to get xelatex on macos?

**Comment by mikewesthad** [comment]
Mmm, I'm not on OSX, and like @bilderbuchi said, the PDF generation is probably broken currently, but what happens if you open up terminal and try:
```
xelatex -v
```
If that throws an error, then something might not have been installed properly or xelatex is not in your path variable.

**Comment by mikewesthad** [comment]
I ended up having a mac in front of me (OSX 10.10).  Running through the instructions as listed in the readme worked for getting latex installed.  As expected, the PDF building will error out.  But it didn't (and shouldn't) be erroring out on `xelatex not found`.  I'd sticking with the guess that something went screwy in the installation process for you, or that xelatex didn't get added to terminal's path variable.

**Comment by mikewesthad** [comment]
@mattholl, there's a "working" [branch](https://github.com/openframeworks/ofBook/tree/pdf-generation-fix) which will now build PDFs.  Note: some of the chapters (math, sound and memory) are removed from the build pipeline until they can be fixed.  Also, no guarantees that the formatting is legible throughout
