### ISSUE TITLE
PDF Generation Issues

### ISSUE THREAD

**Issue by mikewesthad** [openframeworks/ofBook#141]
I just pushed a new branch [pdf-generation-fix](https://github.com/openframeworks/ofBook/tree/pdf-generation-fix) for getting the PDF generation limping along.  It's working* again. 

I didn't have time to sort out the issues listed in this commit (a17223874345bedae4bbbb47cdfefe008e73984a), so the memory, sound and math are temporarily cut from the PDF pipeline:
- ~~Sound chapter: uses approximately equal sign within inline code, which
breaks lstinline.  Needs to be changed to \approx at some point in the pipeline.~~
- ~~Math: Similar issues as sound, but more of them.  E.g. dot product character breaks the tex file in multiple places. Also, it has latex code within the chapter, and I'm not sure whether that is problematic.~~
- ~~Memory: uses svg images which latex can't handle by default~~

**Comment by mikewesthad** [comment]
Nevermind.  After pulling the chapters apart and debugging, the only needed change was converting the SVGs in the memory chapter to PDFs.  PDF building is [working](https://github.com/openframeworks/ofBook/releases/tag/0.4.0).

**Comment by tpltnt** [comment]
Cool, thank you for taking care of the pdf generation.

**Comment by bilderbuchi** [comment]
hey @mikewesthad. I just checked the generated pdf, and the git chapter is missing from the generated pdf.

**Comment by bilderbuchi** [comment]
also, will you merge back into master when the pdf generation has been fixed completely?

**Comment by mikewesthad** [comment]
@bilderbuchi, sorry I didn't catch that.  It's in the PDF (p.386), but it didn't get picked up as it's own chapter.  (C++11 got merged in there too.)  I'm guessing there is some improperly formatted markdown in the C++11 chapter.  I'll go investigate now.

As for merging, yeah (assuming that @arturoc signs off on my conversion of his svgs into pdfs).  I also want to double checking that merging this in doesn't break any outstanding PRs first.

**Comment by mikewesthad** [comment]
Yep - inconsistent markdown in ios & c++11 chapters caused chapters to get folded together.  Fixed and release updated

**Comment by bilderbuchi** [comment]
Great, thanks!
