### ISSUE TITLE
typo on chapters/animation.html#background

### ISSUE THREAD

**Issue by whitedryas** [openframeworks/ofBook#151]
If we are 25 percent of the way, it looks like
  ((1-0.75) * A) + (0.25 * B)
which is 75% of A + 25% of B.

=============
Should'nt it be ?
  ((1-0.25) * A) + (0.25 * B)

**Comment by tpltnt** [comment]
Thank you for spotting this error @whitedryas. It is already fixed in pull request #149 i guess. Can you take a look there and tell if you think it is addressed appropriately. If not please let me know.

**Comment by whitedryas** [comment]
I think the issue was properly addressed. Thanking you for your answer.

2015-08-13 23:40 GMT+02:00 tpltnt <notifications@github.com>:

**Comment by tpltnt** [comment]
Ok, i close this issue then. Please report any other weird things you encouter or better send a pull request.
