### ISSUE TITLE
"..." in sound example code blocks can be confusing for new users.

### ISSUE THREAD

**Issue by bakercp** [openframeworks/ofBook#155]
Hey @admsyn hope you're well.  I've got a few students enjoying your sound chapter and as new-ish users translating the abbreviated examples into usable code is proving a bit difficult (the ...) is tripping them up with the inline implementation.  I fixed a few stray typos, which will help a little, but I'm wondering if you would be opposed to being a bit more verbose -- or adding full code examples to the chapter.  Hope you're well and thanks for a great chapter!

**Comment by admsyn** [comment]
Hey @bakercp. Sure, I'll look into this now. I'm pretty sure I did that specifically because it was mentioned in the style guide but it may have been a misreading :)

**Comment by bakercp** [comment]
Ahhh ... style guide ...

**Comment by bakercp** [comment]
I just took a look at the style guide but couldn't find anything that seemed relevant.  Personally I prefer your terse way of doing it.  I think the solution would be to add full code to the `code` folder in the chapter and link to the raw code near the terse versions.

**Comment by admsyn** [comment]
[This bit specifically](https://github.com/openframeworks/ofBook/blob/master/info/editorsGuide.md#variables-functions-and-functions-with-arguments), but I think in this case we can override it by popular demand :)

**Comment by bakercp** [comment]
I think that refers more to in-line (or in-flow) code, whereas I'm talking more about the indented code blocks.  I'd probably just defer to my above comment ... just make a note that the blocks are code fragments to highlight the important bits and then provide a link to the full source.  If you need help getting full source together, I'm happy to.  We're using some of these examples as jumping off points.

**Comment by bakercp** [comment]
Sorry, just to be clear, I'm talking about code blocks like this:

```c++
class ofApp : public ofBaseApp {
  ...
  void audioOut( float * output, int bufferSize, int nChannels );
  double phase;
};

void ofApp::setup() {
  phase = 0;
  ofSoundStreamSetup(2, 0); // 2 output channels (stereo), 0 input channels
}

void ofApp::audioOut( float * output, int bufferSize, int nChannels ) {
  for(int i = 0; i < bufferSize * nChannels; i += 2) {
    float sample = sin(phase); // generating a sine wave sample
    output[i] = sample; // writing to the left channel
    output[i+1] = sample; // writing to the right channel
    phase += 0.05;
  }
}
```

**Comment by admsyn** [comment]
Ah gotcha, how about I rework those to be valid C++, more like this?

```
class ofApp : public ofBaseApp { 
  // … other things ...
  void audioOut( float * output, int bufferSize, int nChannels );
  double phase;
};
```

**Comment by bakercp** [comment]
Yeah, that would be an nice improvement!
