### ISSUE TITLE
Setup() not updated for vector in Ooops! chapter "Make objects on the fly"

### ISSUE THREAD

**Issue by elburz** [openframeworks/ofBook#158]
Under the section: Make Objects on the fly

It is a little confusing whether you should be starting a new ofApp.cpp or continuing with your existing file. The text would have lead you to make the changes to the ofApp.cpp you made in the previous section, but at the moment the ofApp.cpp setup() function never gets updated to address the new use of the myBall vector. Fix could be as simple and mentioning to comment it out all the code in the existing setup() function.

**Comment by bilderbuchi** [comment]
ping @ruxrux

**Comment by tpltnt** [comment]
@elburz can you check if my pull request addresses your issue appropriately?

**Comment by bilderbuchi** [comment]
@elburz @tpltnt closed by #165?

**Comment by elburz** [comment]
yes

**Comment by bilderbuchi** [comment]
thanks!

**Comment by ruxrux** [comment]
thanks you guys for this!
I've been travelling deep on the final stages of a project and only now saw
this!
appreciate your help!!
