### ISSUE TITLE
setup() arguments not addressed in "Quick intro to polymorphism"

### ISSUE THREAD

**Issue by elburz** [openframeworks/ofBook#159]
In the Ooops! chapter, section: Quick intro to polymorphism

We go though removing the arguments in the Ball::setup() but it isn't mentioned that you'd need to update the ofApp.cpp code in the mouseDragged() function, as the tempBall.setup() currently feeds in the three arguments. 

Not sure if it makes more sense to add a note about updating the mouseDragged section to remove the arguments, or if it's better to add a section to override the Ball::setup() in BallBlue with a setup() that doesn't require arguments.

**Comment by bilderbuchi** [comment]
ping @ruxrux

**Comment by tpltnt** [comment]
@elburz can you check #166 as well? Thank you.
