### ISSUE TITLE
Missing () in code example in Animation chapter

### ISSUE THREAD

**Issue by elburz** [openframeworks/ofBook#161]
In the Animation chapter, section: Simple examples

In the first code example:

```
void ofApp::draw(){
    float xPos = ofMap(sin(ofGetElpasedTimef()), -1, 1, 0, ofGetWidth());
    ofRect(xPos, ofGetHeight/2, 10,10);
}
```
```ofGetHeight/2``` should be ```ofGetHeight()/2```

**Comment by tpltnt** [comment]
Good catch! I changed it and it is currently in review by @ofZach (as he checks the whole chapter).
