### ISSUE TITLE
animation chapter - weird time based animation example

### ISSUE THREAD

**Issue by arturoc** [openframeworks/ofBook#164]
At the end of the introduction it explains briefly time based animation:

> Typically more complex animation will be written to take this into account, either by using functions like time (explained below) or mixing the frame rate or elapsed time into your update. For example, a solution might be something like:

```
void testApp::update(){
    xPos += 0.5 * (30.0 / ofGetFrameRate());
}
```

the example is kind of strange since ofGetFrameRate is an aproximation and usually filtered so it won't correspond with the real timing and can result in stuttery animation. wouldn't it be better to use ofGetTimeLastFrame()?

```
void testApp::update(){
    xPos += ofGetTimeLastFrame() * speed;
}
```

**Comment by ofZach** [comment]
yeah that makes sense...   In practice I haven't seen this jerky animation, but it makes sense to use ofGetTimeLastFrame instead of ofGetFrameRate()....

**Comment by tpltnt** [comment]
@arturoc @ofZach i updated the docs

**Comment by mattfelsen** [comment]
Small note, the function is `ofGetLastFrameTime()` rather than `ofGetTimeLastFrame()`. @tpltnt can you update your PR?

**Comment by tpltnt** [comment]
@mattfelsen this should already be fixed see https://github.com/tpltnt/ofBook/commit/e8812967184fa4be3ab012dca661700c6d80dba6

**Comment by mattfelsen** [comment]
Ah, sorry I missed it, thanks :smile:
