### ISSUE TITLE
graphics chapter

### ISSUE THREAD

**Issue by arturoc** [openframeworks/ofBook#17]
i think there might be some explanations about ofMesh, ofPolyline, ofPath, ofVboMesh, ofNode

How to go from using ofTranslate/Rotate/Scale to using ofNode. The difference between ofMesh/ofVboMesh

Also going from immediate mode with ofBegin/End to using ofPath, see how ofPath tessellates and stores that so you can create a shape at the beginning of the application and draw it several times...

this could even be a 2nd part, like advanced graphics or something like that

**Comment by tpltnt** [comment]
This issue seems to be resolved since the discussion went quiet and the "introduction to graphics" as well as the "advanced graphics" chapters are in place.
