### ISSUE TITLE
Crash on ofLight in A Basic 3D Scene section in graphics

### ISSUE THREAD

**Issue by mikechambers** [openframeworks/ofBook#197]
I am working through the graphics section of ofBook in order to get a basic understanding of how to use 3D.

I am creating the app in the **A Basic 3D Scene** section, and when I try to compile, it is crashing the app.

```
#include "ofMain.h"
#include "ofApp.h"

//========================================================================
int main( ){
    ofGLFWWindowSettings settings;
    settings.setGLVersion(3, 2);
    settings.width = 1280;
    settings.height = 720;
    ofCreateWindow(settings);

    ofRunApp(new ofApp());
}
```

The crash (EXEC_BAD_ACCESS, code=1, address=0x0) is on this line:

```
shared_ptr<ofBaseRenderer> & ofGetCurrentRenderer(){
    return mainLoop()->getCurrentWindow()->renderer();
}
```

in ofAppRunner.cpp

This is OS X 10.11.4 in XCode 7.3

If I comment out my ofLight declaration in ofApp.cpp, then the crash goes away and the app runs.

```
// Add this in the App.h
ofLight light;
ofEasyCam cam;

// add these lines to the setup and to the draw method in the App.cpp
void ofApp::setup(){
    light.setup();
    light.setPosition(-100, 200,0);
    ofEnableDepthTest();
}

void ofApp::draw(){
    cam.begin();
    // here you will draw your object
    cam.end();
}
```

Known issue? Any workaround would be appreciated.

**Comment by hamoid** [comment]
This happens to me too, if I ignore the "Add this in the App.h" comment. 

Did you maybe leave those two lines in the cpp file?

**Comment by arturoc** [comment]
as the comment says that should go in the .h not in the cpp. if you put it in the cpp it'll be statically initialized before the opengl context is created which will make the app crash. going to close this but feel free to reopen if it still happens when moving it to the .h file
