### ISSUE TITLE
Function notation

### ISSUE THREAD

**Issue by OmerShapira** [openframeworks/ofBook#20]
So far I've taken the approach of putting the function signature in the head of a specific chapter, like so:
#### Affine Mapping: The `ofMap`
`float ofMap(float value, float inputMin, float inputMax, float outputMin, float outputMax, bool clamp = false)`

adding the default params for better understanding. I don't know if others are doing it, but if this doesn't become a standard, what is the standard for doing so?

**Comment by tpltnt** [comment]
The info/editorsGuide.md touches on this i believe. Do you think there is more need for discussion or can this issue be closed?

**Comment by bilderbuchi** [comment]
if there is a need for more discussion, we can always reopen it. :-)
