### ISSUE TITLE
Generating Meshes Chapter : Broken Image Link

### ISSUE THREAD

**Issue by mikechambers** [openframeworks/ofBook#201]
http://openframeworks.cc/ofBook/chapters/generativemesh.html

In the "Generative Mesh: Using an image to drive the creation of a mesh" section. There is a link to download the PNG of the hubble telescope image.

> (Click here, then right-click the image and "save as image.")

The generated link is incorrect, and redirects to the openframeworks main page. The link it points to is:

http://openframeworks.cc/images/stars.png

It should point to:

http://openframeworks.cc/ofBook/images/generativemesh/images/stars.png

**Comment by mikewesthad** [comment]
@mikechambers thanks for catching that!  Relative hyperlinks don't play nicely with the build system.
