### ISSUE TITLE
Brushes with Basic Shapes - Warning message re QTKit and OSX 10.9

### ISSUE THREAD

**Issue by imagineeringio** [openframeworks/ofBook#209]
Hi,
First let me say thank you so much to everyone involved in putting this book together. It is fantastic.]

Im hoping I can get some help with an example Brushes with Basic shapes, giving me an warning message preventing compile.

OSX: 10.11.2
Xcode version: 6.3.2
OF version: of_v0.9.3

File: ofQTKitGrabber.mm
Error message: #warning Using QTKit, which is deprecated in OSX 10.9

Is there a workaround a simpleton like myself can use? Although its just a warning, it seems to be preventing it from running, unless something in the ofBook that Im missing.

Many thanks
Simon

**Comment by ofZach** [comment]
thanks for the feedback ! 

the warning shouldn't matter (warnings are just telling you that something is deprecated).  do you see any messages in red?  this is also a good forum question (vs the github repo) since I think this is more about how to use / compile OF vs the content of the book.

**Comment by imagineeringio** [comment]
Thank you! I thought it might be user generated!.

I'll head on over to the forums and leave you good people to what you do best.

Cheers
Simon
