### ISSUE TITLE
ToC accordion never scrolls; items on the bottom are obscured

### ISSUE THREAD

**Issue by GreekFellows** [openframeworks/ofBook#210]
The accordion on the left side of every page that serves as the table of contents is never scrolled. As a result, when the accordion is expanded at a deep level, or at a part with many chapters, the items on the bottom of the accordion are never visible.

![image](https://cloud.githubusercontent.com/assets/6222896/16177466/402d6a28-3669-11e6-9a39-316e9f26e9a0.png)

This is when the reader is at Basics > Ooops! > Overview. Items below "Approaches" are all obscured. Although the reader can see other items by clicking on "Approaches" - thereby collapsing the long "Basics" and expanding the much-shorter "Approaches" - IMHO this is inconvenient to the reader.

A possible simple fix is making the expanded accordion item collapsible by clicking on it. This allows the reader to make the accordion fully visible when in need to do so. However, considering the potential development of this project which may make the table of contents longer, enabling scroll of the accordion is probably a better idea in the long run.

**Comment by mikewesthad** [comment]
@GreekFellows good point. I just implemented the simple fix version (8170b3b5c94f904d0004a57c91c198d849385654) of making the currently selected item collapsible. I agree that as the sidebar continues to grow, we'll need a more robust solution. Making the sidebar scrollable, independent of the chapter text, sounds like a good direction.
