### ISSUE TITLE
See ofPtr - Broken link in chapter C++ -  Sorting and shuffling a vector - Vectors of objects

### ISSUE THREAD

**Issue by fdiba** [openframeworks/ofBook#211]
Here is a link that is broken in chapter C++ -  Sorting and shuffling a vector - Vectors of objects

> Note that this means erase and remove_if demonstrated above will not be sufficient. If pointers are needed, it is worthwhile to consider using shared pointers instead. [See ofPtr](http://openframeworks.cc/documentation/types/ofPtr)

**Comment by arturoc** [comment]
yes ofPtr was deprecated last version and won't appear in the docs probably. the link should point to shared_ptr in some c++ documentation perhaps or just remove it by now. do you want to send a fix?

**Comment by fdiba** [comment]
Thank you for your answer. I did send a pull request.
