### ISSUE TITLE
Sidebar menu does not expand/collapse on click

### ISSUE THREAD

**Issue by davidbeermann** [openframeworks/ofBook#225]
Right now nothing happens when you click on any of the main items in the collapsible menu. It really is a just a minor JavaScript error: the callback function for the jQuery click handler is missing the event argument.

```js
// missing event argument...
$(".group").click(function() {
  // ...leads to JS exception here.
  var newSelected = event.currentTarget;
  // ...
});
// this fixes the issue
$(".group").click(function(event) {
  var newSelected = event.currentTarget;
  // ...
});
```

**Comment by mikewesthad** [comment]
Ek! Good catch - thanks! It's fixed now.

It's odd, apparently Chrome and some other browsers have a global `event` variable, so this bug didn't break ofBook until I opened it up in Firefox.
