### ISSUE TITLE
Typo in Advanced graphics>3D>ofMatrix4x4 example

### ISSUE THREAD

**Issue by janus2** [openframeworks/ofBook#228]
In the example in Advanced graphics>3D>ofMatrix4x4, I think the correct invocation of the method m.rotate(45,0,0,0) should be m.rotate(45,0,0,1).
Otherwise the square has no rotation.
Let me no if I am wrong.

Thanks.

**Comment by arturoc** [comment]
you are correct, do you want to send a fix? thanks!
