### ISSUE TITLE
Some links are broken

### ISSUE THREAD

**Issue by cgiles** [openframeworks/ofBook#236]
When I try to access the ofbook from there : http://openframeworks.cc/learning/#ofBook , most of the links point to the of homepage.

by example : http://openframeworks.cc/ofBook/chapters/hardware.html

**Comment by bakercp** [comment]
Same issue here https://github.com/openframeworks/ofSite/issues/559

**Comment by ofZach** [comment]
this appears to be a server issue, working on it...   

![398533_pikaconstruction](https://cloud.githubusercontent.com/assets/142897/18847330/cecfec7a-83f7-11e6-8b0d-414e83f23667.gif)

**Comment by tpltnt** [comment]
Things seemed to be fixed. I tested all links mentioned here. How about closing this issue?

**Comment by ofZach** [comment]
sure, closing!
