### ISSUE TITLE
chapter 1 and 3 overlapping topics

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/ofBook#24]
Hey @ofZach 
I can see in chapter 1 that there are several topics that I have to cover, as part of my chapter "project structure and setup", I think that the intro you already have is good enough, just leaving it on the abstract side of things, opposed to my chapter  which is totally pragmatic. I'm already adding to my chapter the following topics that you have listed in yours. So, shall I cover these topics, and leave them out from yours? (It will also make my writing easier as I need to explain them).
OF structure
project generator
.h and .cpp
setup/update/draw
first project a circle moving in the screen (I didn't had in mind this one but wont hurt adding it)
scary things in OF code (#ifdefs pragma once...)
preprocessor/compiler/linker

best

**Comment by tpltnt** [comment]
@roymacdonald is this still an issue after one year? If not this issue should be closed.
