### ISSUE TITLE
ofBook Sound chapter loadSound() depricated

### ISSUE THREAD

**Issue by Simplelenz** [openframeworks/ofBook#272]
I am using open frameworks in my mac. When I was following the Sound chapter in ofBook, it uses loadSound() function to load sounds but Xcode suggests that it is deprecated.

**Comment by icq4ever** [comment]
it changed from `loadSound()` to  `load()`.
http://openframeworks.cc/documentation/sound/ofSoundPlayer/#show_load

**Comment by Simplelenz** [comment]
you can close this thread updating the ofBook documentation. Thanks

**Comment by admsyn** [comment]
fixed in e5c87b70db9edec1b907d2e92fe9c96085bdb895

thanks!
