### ISSUE TITLE
Typo in Ooops!

### ISSUE THREAD

**Issue by agatheblues** [openframeworks/ofBook#287]
- In the section 'Make objects on the fly', there is 'we them define', it should be 'we then define' !
- In the section 'Making and delete as you wish...', there is 'we will loop though our vector', it should be 'we will loop through our vector'.

That's it :)
Content is super cool so far, thanks !

**Comment by montoyamoraga** [comment]
@roymacdonald this issue can be sloed because of #326 :)

**Comment by roymacdonald** [comment]
gracias @montoyamoraga
