### ISSUE TITLE
Broken link in ofBook, Brushes From Freeform Shapes

### ISSUE THREAD

**Issue by wuhnder** [openframeworks/ofBook#289]
It's under the heading "Building a Brush from Polylines"

> This isn't the same kind of vector that we talked about earlier in the context of of2Vecf. If you haven't seen vectors before, check out the **stl::vector basics tutorial** on the site.

The text in bold above links to [http://openframeworks.cc/tutorials/c++%20concepts/001_stl_vectors_basic.html](http://openframeworks.cc/tutorials/c++%20concepts/001_stl_vectors_basic.html) (broken)

Correct link (I think) is:
[http://openframeworks.cc/ofBook/chapters/stl_vector.html](http://openframeworks.cc/ofBook/chapters/stl_vector.html)

**Comment by mikewesthad** [comment]
@wuhnder Much appreciated - thanks!
