### ISSUE TITLE
Editing/Author Guide

### ISSUE THREAD

**Issue by brannondorsey** [openframeworks/ofBook#30]
Ive drafted an [Editing Guide](https://github.com/brannondorsey/ofBook/blob/master/editorsGuide.md) to help get all of us editors on the same page. I wanted to propose it for discussion before pushing it to the repo and calling it official. If it is generally OK I can push it to the repo and then everyone can make changes as they see fit.

Thoughts?

**Comment by tpltnt** [comment]
Is this issue still being worked on? If everything is resolved it should be closed.
