### ISSUE TITLE
C++ Basics Draft Feedback

### ISSUE THREAD

**Issue by mikewesthad** [openframeworks/ofBook#31]
@jtnimoy I just got a chance to give your draft a close read.  It's definitely great so far - easy to read and entertaining (Back to the Future reference is my favorite).  

Your figures that explore the code visually (e.g. figs 11, 18, 21, etc.) will be a huge boon for those readers who are coding for the first time.  Figs 28 + 29 are simple examples that are particularly effective.  They help elucidate what is going memory-wise with just a few extra marks+words, and that's great for helping beginners see "beyond" the code to what is happening underneath.  

I like ideone though I did run into a bug (that I couldn't replicate).  Changes to the code wouldn't get compiled into the version that was being run.  Tried saving, running multiple times, making multiple edits.  I ended up chalking it up to having the page open to long and just refreshed it to get it working again.  

I think it would be cool if your chapter had some companion site (or oF app) that would animate the ASCII output your code generates in ideone.  Having to scroll is completely fine, so this is wish list type stuff, but being able to copy+paste the output into a textbox and then watching it move would be pretty cool.  (Esp for your prime "random" generator.)  An alternative might be to just include a few animated gifs.

I think a couple sections could use a conceptual introduction before jumping into code.  The functions section comes to mind.  It wouldn't require more than a sentence or two talking about what a function is, even if it is just from an english dictionary perspective.  It would help orient readers for what is coming next.  Same idea goes for the Variables (part 1) section and for the looping section.

Your email to the ofBook list mentioned cutting signed/unsigned and leaving out bitwise operators.  That seems fine to me, and I take the silence on the email front as confirmation from the rest of the group?  There could be a section at the end of the chapter where you just show some syntax, drop names/concepts and say where to go to find more info.  That would arm readers with enough knowledge to feel comfortable diving into those things should they come across them in someone's code.

I feel mixed about the twitter thing since it feels a bit forced and transparent in that it is just about promoting ofBook.  It might feel more appropriate in a place like at the end of your ball animation where you ask the reader to tackle some extensions.  Or if you were to suggest they design their own random functions and then tweet a link to their ideone code (or a screenshot/gif of their stdout).  Etc.

You jump into discussion about compiling and precompiling pretty quickly, which makes sense, but it could benefit from a simply flow chart thrown in there.  Something that shows what happens to your code, so that newbies who aren't familiar with compiling have some visuals to grab on to.

For your namespaces analogies, the 3rd grader bus paragraph had plenty of character, but I found it distracted from the point.  Maybe you could merge that seat space conflict analogy with your second namespace analogy by focusing on school buses.  Multiple buses: there can be people with the same name, but on different buses, etc.  

I think the namespace section points out a tricky balance you are trying to strike.  In namespace, you are referencing things like `ofBackground` and `glBlendMode` for the benefit of advanced readers, but also trying to not overwhelm readers who don't yet know what a variable or function is.  Another example of this is Fig 10 where you are introducing types and functions before handling variables.  You've set up a flow where you explain every line in the hello world code before really getting into variables.  

One approach to tailoring that balance to beginners might be to lead the chapter with variables (logic of single lines of code), then work your way into functions (chunks of code), then all the other goodies like precompiling, namespaces, etc.  That would just require letting the reader know to ignore `#include <iostream.h>`, `using namespace std;` for the moment and just focus in on what is happening within the `{ }`.  Then the concepts reveal themselves in a way that allows them to build upon each other (or at least, that's how I imagine it happening in the brain of someone just learning to code).

Anyway, those were the big notes that I wrote down while reading.  I'll throw in some inline comments into your chapter for smaller things.  Again, chapter is great so far!

**Comment by tpltnt** [comment]
@jtnimoy did you push the changes @ofZach mentioned? If so this issue should be closed.
