### ISSUE TITLE
ofbook - C++ Language Basics deprecated header calls

### ISSUE THREAD

**Issue by dsvid** [openframeworks/ofBook#312]
Just wanted to point out that the #include functions in the C++ Language Basics are deprecated and will not compile on ideone.com

For example if you use

`
#include <iostream.h>
`

on ideone.com the code will note compile

if the header is changed to:

`
#include <iostream>
`

Then the code compiles.

Not a big deal, but it could be confusing for newcomers.

**Comment by roymacdonald** [comment]
Thanks. Can you make a PR with the necessary changes?

**Comment by dsvid** [comment]
sure, I've just made a pull request here https://github.com/openframeworks/ofBook/pull/313

**Comment by roymacdonald** [comment]
Just merged. Thanks

**Comment by montoyamoraga** [comment]
@roymacdonald this issue can be closed because of #313  right? :)

**Comment by roymacdonald** [comment]
@montoyamoraga gracias. :)
