### ISSUE TITLE
Intro suggestion

### ISSUE THREAD

**Issue by kaylalewis** [openframeworks/ofBook#32]
The intro and oF mission statement gives a good picture of openFrameworks. However, I’d consider explicitly addressing how the book itself is being written by a group of people, each contributing chapters. This isn’t very common–at least for programming books I’ve seen. I can see where having a different voice in each chapter could pose an inconsistency that could be frowned upon. BUT we can play into this by stressing how the oF community “thrives” off many people working together to contribute something greater. 

How are all of these different voices affecting a newcomer to oF? Maybe stressing that yes, chapters were written by different people but we’ve all had access, read, and edited each other’s will help promote this open source community. Chapters have received a lot of feedback but will still emerge with the voice of the author…this can be compared to the oF community that wants to help others with projects without muting the vision of the person proposing the idea, even if they are less skilled in the art of computer programming. There’s no hierarchy, we’re just all working together (at least, that’s the goal).

**Comment by tpltnt** [comment]
Do you @kaylalewis @Onna-no-hito and @bilderbuchi think this issue is addressed properly in the foreword? If no, please leave notes. If yes, please close this issue.

**Comment by bilderbuchi** [comment]
as this issue stems from a time when there wasn't even a foreword, I think this can be safely closed
