### ISSUE TITLE
splitting Chapter 2 into smaller chapters

### ISSUE THREAD

**Issue by jtnimoy** [openframeworks/ofBook#40]
ok, I took a look at the PDF and I think my chapter will breakdown into 5 smaller chapters. I'm going to try and call them "Intro to C++ part 1", "Intro to C++ Part 2", etc. I hope that is acceptable, realizing we're trying to keep it at group effort. If I'm lucky, I'll be able to nickname each of the 5 parts.

The alternative is to write a succinct little advertisement for the real book references, and that doesn't warrant even a single chapter.

**Comment by tpltnt** [comment]
Is this issue still relevant given that one year has passed and things moved along? Please speak up until 2015-06-01 or otherwise i am going to close this issue.

**Comment by ofZach** [comment]
I think this issue is resolved....

**Comment by roymacdonald** [comment]
+1

*Roy Macdonald*
+569 8248 8478
