### ISSUE TITLE
Chapter 3 editing updates

### ISSUE THREAD

**Issue by kaylalewis** [openframeworks/ofBook#51]
Roy,

I went through your chapter thus far and changed some sentence structures and wording. I tried to omit words that just add fluff to sentences to make explanations more concise and understandable. The chapter is laid out well and I look forward to reading the rest. I'd think more into unifying list formats to make them more cohesive. Great job!

**Comment by tpltnt** [comment]
@roymacdonald is this still an issue or can it be closed?

**Comment by roymacdonald** [comment]
I'll close it. Thanks for bringing it up.
