### ISSUE TITLE
Help: IDE Screenshots and tips

### ISSUE THREAD

**Issue by roymacdonald** [openframeworks/ofBook#52]
Hi everyone,
I need to ask for some help.
I'm writing chapter 3 setup and project structure. In it I explain how to start using OF in each IDE. 
What I need to ask you is if you can provide me with a simple screenshot of Eclipse on Linux with the emptyExample opened.
Something like this https://github.com/openframeworks/ofBook/blob/master/03_setup_and_project_structure/images/xCodeScreenShot.jpg
If you can please push the screenshot to 
https://github.com/openframeworks/ofBook/blob/master/03_setup_and_project_structure/images folder.

On the other hand, are there any tips or things I should mention that the user must do in order to run an example for the first time? In particular for Eclipse on Linux and C::B.
For example, to run any example using Xcode you must change the compile target from openFrameworks to the example. I mention it here https://github.com/openframeworks/ofBook/edit/master/03_setup_and_project_structure/chapter.md#L70

I'll really appreciate any help.

All the best!

**Comment by tpltnt** [comment]
@roymacdonald shouldn't this issue be closed given the contribution of @bilderbuchi ?

**Comment by roymacdonald** [comment]
Hey @tpltnt,  thanks for bringing this forwards.
I was just checking and at some point @ofZach removed the placeholder for this screenshot, as well as the part which mentioned eclipse as another possible IDE. I can't recall if this was because eclipse is not officially supported other than for android development or because of something else.
I'll check this a more thoroughly and see what's going on.
Besides all this, I think that this issue should be closed.
Best!
