### ISSUE TITLE
Footnotes / sidebars / asides

### ISSUE THREAD

**Issue by admsyn** [openframeworks/ofBook#54]
So I looked around a bit and I'm not sure this was ever brought up? Maybe I missed the memo :)

I have a few "footnotes" in the sound chapter that are small elaborations on the subject matter, but would be too overkill to include inline. I see @arturoc is [using quote levels](https://github.com/openframeworks/ofBook/blob/master/21_advanced_graphics/chapter.md) for the same thing, is that the way to go?

**Comment by tpltnt** [comment]
Is this an issue that still needs attention? Given that the core issue seems to be resolved and that this thread has been quiet for a few month, i would like to close it on 2015-06-05. Please speak up if you think that is issue still needs eyeballs and action.
