### ISSUE TITLE
For the groups talking about OSC

### ISSUE THREAD

**Issue by Onna-no-hito** [openframeworks/ofBook#6]
three chapters give mention to OSC--

Phoenix (Game Design) will be covering it in-depth, followed by Caitlin/Pierre (Hardware) and Eva's Project Breakdown. You guys should check in with each other, depending on your specific use-case, you can perhaps reference Phoenix's chapter/section without repeating the same text.

**Comment by tpltnt** [comment]
Is this issue still at hand or can it be closed?

**Comment by tpltnt** [comment]
I went through the networking chapter and also improved its OSC section (see #138). I am going to give this issue a moratorium until 2015-06-01. If nobody speaks up, i am going to close this issue then.

**Comment by tpltnt** [comment]
Nobody spoke up, closing the issue according
