### ISSUE TITLE
Game Design Chapter

### ISSUE THREAD

**Issue by kaylalewis** [openframeworks/ofBook#61]
This chapter is fantastic. It's very strategic and clearly written. I had a few suggestions and minor corrections but there is nothing pressing that I can find. 

Some parts used "we" talking at the viewer as though there are multiple writers–which there are–so I'd introduce the chapter with a little background on Code Liberation Foundation, which is a great organization to make people aware of anyway. 

Since it is pretty dense, I would suggest adding a little more positive reinforcement toward the end. Those following the tutorial will probably be exhausted (in the best way possible) by the end, so hearing something like "You made it!" can be helpful. I'm not a fan of sappy writing, but I think in this scenario an occasional pat on the back is necessary as the chapter comes to a close. I actually followed the tutorial for the beginning parts, and they worked fine. I'm going to make it a point to follow all the way through and give more feedback then. 

Again, really impressive.

**Comment by tpltnt** [comment]
I just merged your helpful contributions to the game design chapter. Thank you again. 
Since I can not derive any further action from this ticket I am closing it. If i missed something, please open a new ticket.
