### ISSUE TITLE
Chapter Order

### ISSUE THREAD

**Issue by mikewesthad** [openframeworks/ofBook#63]
With the coming release, maybe it's time to renumber some of the chapters.  The thread in issue #12 left the ordering at this (to guide beginners through a core set of fundamentals):

1. Intro
2. C++ Basics
3. Setup and Project Structure
4. Introduction to Graphics 
5. OOPs!
6. Animation
7. Advanced Graphics
8. Memory
9. Network
10. Threads

Hardware, image processing, data vis, game design, sound, ios, c++11, version control, math chapters, project elliot, project eva, project joel and project memo(?) should be on that list.  (05_Media, 07_interaction_leaving_the_screen, 13_android, 14_arm_linux and 19_shaders are chapterless, so i'm leaving those out.)

Thoughts?

**Comment by tpltnt** [comment]
Is this still an issue given that issue #12 seems to be settled ? If there isn't any veto, this issue should be closed.

**Comment by bilderbuchi** [comment]
closing this, see #12
