### ISSUE TITLE
For groups talking about classes, comparing languages

### ISSUE THREAD

**Issue by Onna-no-hito** [openframeworks/ofBook#7]
A couple chapters discuss how classes work:
JTNimoy (C++ Basics), Rui (OOPs)

and several chapters give mention to C++ versus other langauges:
JTNimoy (C++ Basics), Rui (OOPs),  Lukasz (iOS), Arturo (Android--java)

just wanted you guys to check-in with each other to possibly save yourselves time
and not repeat the same explanations.

some questions:
is it more fitting for Rui to talk about classes when explaining OOP?
should the OOP chapter come before the C++ chapter?

Josh-- do you cover differences between Obj.C and Java?
obviously Lukasz and Arturo-- you get more in-depth as far as use case but for the
basics differences of the languages maybe Josh has that covered?

**Comment by tpltnt** [comment]
Do you people think this is still an issue? If not I suggest to close this issue. @Onna-no-hito could you do that?

**Comment by tpltnt** [comment]
This thread seems to be stale since over a year. It also does not have an actionable outcome (anymore). Hence I close it.
