### ISSUE TITLE
joel project break down 

### ISSUE THREAD

**Issue by ofZach** [openframeworks/ofBook#9]
hey joel, can you tighten up your outline?   ie, take the three projects and maybe elaborate on how you would write about them?  I think it will help here.  The other material (such as things for other parts of the book) is probably useful on the hackpad (or talk to other chapter authors), but it would be good to get an as detailed as possible outline regarding the projects you want to discuss.

**Comment by tpltnt** [comment]
Has this been done? If so this issue should be closed.

**Comment by JGL** [comment]
Yup.
> On 16 Apr 2015, at 16:28, tpltnt <notifications@github.com> wrote:
> 
> Has this been done? If so this issue should be closed.
> 
> —
> Reply to this email directly or view it on GitHub.
> 


Joel Gethin Lewis
me@joelgethinlewis.com
@joelgethinlewis
+44 7932 792 076

**Comment by tpltnt** [comment]
Please close this issue @openframeworks/ofBook . Thank you!

**Comment by tpltnt** [comment]
@ofZach please close this issue. Thank you!
