### ISSUE TITLE
HTML styled images in Network, Memory in C++, Threads

### ISSUE THREAD

**Issue by mikewesthad** [openframeworks/ofBook#94]
@arturoc, you used HTML to control the size of your images in the markdown for your chapters.  Those don't get converted into figs by pandoc and are then missed in the python script, so they don't load in the web book.  Can we switch over to markdown syntax for those chapters?  (If you still want 300px images, you can save out 300px versions of your images, and the CSS will load them without stretching.)

**Comment by arturoc** [comment]
i had to use html because i was using svgs but yes whatever fixes it is ok. i used svgs thinking that in case we end up printing it or whatever it would be better to have the vectorial info but if it's problematic it's totally ok to transform them into images

**Comment by mikewesthad** [comment]
Ohhhh, I didn't realize that github markdown doesn't render svgs.  I see.  (I've been using an offline editor that handles svgs.)

Since we have the web book link, I don't think we have to worry about people reading the markdown right now.  I just switched things over to the markdown syntax, so they'd render in the web book.  They are pretty large images (dimension-wise), so they might fit better in the chapters if they were rendered out at something like 400px.
